/**
 * Environment variable validation.
 *
 * ARCHITECTURAL RESPONSIBILITY
 * Parses `process.env` exactly once at process start and refuses to boot on
 * invalid configuration. A typo in `DATABASE_URL` should be a startup failure
 * naming the variable — not a confusing error an hour later under load.
 *
 * SECURITY CONSTRAINTS
 *  - Error messages name the offending KEYS and never print their VALUES; an
 *    environment error frequently ends up in a log aggregator or a screenshot.
 *  - Production rejects the placeholder `SESSION_SECRET` shipped in
 *    `.env.example`, so a deployment cannot inherit a publicly known secret.
 *  - This module is SERVER ONLY. It is exported under a separate entry point
 *    (`@growth-os/contracts/env`) so that importing the package from a client
 *    component cannot pull secrets into a browser bundle.
 *
 * @see docs/decisions/ADR-0010-validation-and-contracts.md
 * @see docs/engineering/environment-management.md
 */

import { z } from 'zod';

/**
 * Is this origin one the browser treats as a secure context?
 *
 * https always is. So is loopback: browsers grant `http://localhost` and
 * `http://127.0.0.1` secure-context status, and `Secure` cookies work there.
 *
 * The carve-out exists because a production BUILD is routinely run locally —
 * by the E2E suite, and by anyone verifying production behaviour before
 * deploying. Rejecting loopback would force those runs onto the development
 * server, which has materially different CSP requirements, so we would be
 * testing a configuration that never ships.
 *
 * A real deployment cannot exploit this: `http://127.0.0.1` is not reachable
 * by a customer.
 */
function isSecureOrigin(url: string): boolean {
  if (url.startsWith('https://')) return true;
  try {
    const { hostname, protocol } = new URL(url);
    return protocol === 'http:' && (hostname === 'localhost' || hostname === '127.0.0.1');
  } catch {
    return false;
  }
}

/** The placeholder shipped in `.env.example`. Must never reach production. */
const PLACEHOLDER_SESSION_SECRET = 'replace-me-with-32-bytes-of-base64-entropy';

const nodeEnvSchema = z.enum(['development', 'test', 'production']).default('development');

/** Coerce a decimal string to a positive integer, with a default. */
const positiveInt = (fallback: number) => z.coerce.number().int().positive().default(fallback);

const baseEnvSchema = z.object({
  NODE_ENV: nodeEnvSchema,

  APP_URL: z
    .url('APP_URL must be an absolute URL, e.g. http://localhost:3000')
    .refine((value) => !value.endsWith('/'), 'APP_URL must not have a trailing slash'),

  DATABASE_URL: z.string().min(1, 'DATABASE_URL is required'),
  DATABASE_POOL_MAX: positiveInt(10),

  /**
   * Minimum 32 characters rather than 32 decoded bytes: the value is used as
   * HMAC key material, where any sufficiently long high-entropy string is
   * acceptable. Requiring valid base64 would reject perfectly good secrets
   * generated by other tools.
   */
  SESSION_SECRET: z.string().min(32, 'SESSION_SECRET must be at least 32 characters'),
  SESSION_IDLE_TTL: positiveInt(60 * 60 * 24 * 30),
  SESSION_ABSOLUTE_TTL: positiveInt(60 * 60 * 24 * 90),

  RATE_LIMIT_DRIVER: z.enum(['memory', 'redis']).default('memory'),
  RATE_LIMIT_LOGIN_MAX: positiveInt(8),
  RATE_LIMIT_LOGIN_WINDOW_SECONDS: positiveInt(900),

  /**
   * Public form submission limits, per hour, plus the in-process burst tier.
   *
   * Configuration rather than constants for two honest reasons: a customer
   * running a genuinely high-traffic campaign will exceed 200 an hour on one
   * form, and the E2E suite drives far more submissions from one loopback
   * address in two minutes than any visitor does.
   *
   * `positiveInt` means these can be RAISED or LOWERED but never set to zero or
   * disabled — there is no value of this configuration that turns the limiter
   * off, which is the property that makes it configuration and not a switch.
   */
  PUBLIC_SUBMISSION_MAX_PER_IP_FORM: positiveInt(5),
  PUBLIC_SUBMISSION_MAX_PER_IP: positiveInt(20),
  PUBLIC_SUBMISSION_MAX_PER_FORM: positiveInt(200),
  PUBLIC_SUBMISSION_BURST_MAX: positiveInt(5),

  LOG_LEVEL: z.enum(['trace', 'debug', 'info', 'warn', 'error']).default('info'),
  LOG_FORMAT: z.enum(['json', 'pretty']).default('pretty'),

  /**
   * Set only when the app runs behind a proxy we control. Until then,
   * `X-Forwarded-For` is attacker-controlled and is ignored for rate limiting.
   */
  TRUSTED_PROXY: z
    .string()
    .optional()
    .transform((value) => value === 'true' || value === '1'),
});

const envSchema = baseEnvSchema
  .refine((env) => env.SESSION_ABSOLUTE_TTL >= env.SESSION_IDLE_TTL, {
    message: 'SESSION_ABSOLUTE_TTL must be greater than or equal to SESSION_IDLE_TTL',
    path: ['SESSION_ABSOLUTE_TTL'],
  })
  .refine(
    (env) => env.NODE_ENV !== 'production' || env.SESSION_SECRET !== PLACEHOLDER_SESSION_SECRET,
    {
      message: 'SESSION_SECRET is still the example placeholder. Generate a real secret.',
      path: ['SESSION_SECRET'],
    },
  )
  .refine((env) => env.NODE_ENV !== 'production' || isSecureOrigin(env.APP_URL), {
    message:
      'APP_URL must use https in production (session cookies are Secure-only). ' +
      'http is permitted only for loopback hosts.',
    path: ['APP_URL'],
  })
  .refine((env) => env.RATE_LIMIT_DRIVER !== 'redis', {
    // Fail loudly rather than silently falling back to the in-memory driver,
    // which would leave an operator believing they had distributed limiting.
    message: 'RATE_LIMIT_DRIVER=redis is not implemented yet. See ADR-0009.',
    path: ['RATE_LIMIT_DRIVER'],
  });

export type Env = z.infer<typeof envSchema>;

let cached: Env | null = null;

/**
 * Parse and cache the environment.
 *
 * Cached because validation is pure and the environment does not change during
 * a process lifetime; re-parsing on every call would put Zod on hot paths.
 *
 * @throws Error naming the invalid keys — never their values.
 */
export function loadEnv(source: NodeJS.ProcessEnv = process.env): Env {
  if (cached) return cached;

  const parsed = envSchema.safeParse(source);
  if (!parsed.success) {
    const problems = parsed.error.issues
      .map((issue) => `  - ${issue.path.join('.') || '(root)'}: ${issue.message}`)
      .join('\n');
    throw new Error(
      `Invalid environment configuration:\n${problems}\n\n` +
        'See .env.example and docs/operations/local-development.md.',
    );
  }

  cached = parsed.data;
  return cached;
}

/** Test-only: drop the cache so a test can supply a different environment. */
export function resetEnvCache(): void {
  cached = null;
}

/**
 * Whether session cookies should carry the `Secure` attribute.
 *
 * Derived from `APP_URL` rather than `NODE_ENV` so that a production-like
 * local build over http still works, while any https deployment gets `Secure`
 * automatically. Tying this to NODE_ENV is a common source of "cookies stopped
 * working in staging" incidents.
 */
export function shouldUseSecureCookies(env: Env): boolean {
  return env.APP_URL.startsWith('https://');
}
